/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author josej
 */
public class frm_traductor extends javax.swing.JFrame {

    private File currentFile;
    
    /**
     * Creates new form frm_traductor
     */
    public frm_traductor() {
        initComponents();
        jmi_copiar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, KeyEvent.CTRL_DOWN_MASK));
        jmi_cortar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, KeyEvent.CTRL_DOWN_MASK));
        jmi_pegar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_P, KeyEvent.CTRL_DOWN_MASK));
        jmi_buscar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_B, KeyEvent.CTRL_DOWN_MASK));
        jmi_reemplazar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R, KeyEvent.CTRL_DOWN_MASK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_texto = new javax.swing.JTextField();
        btn_procesar = new javax.swing.JButton();
        txt_longitud = new javax.swing.JTextField();
        txt_totalPalabras = new javax.swing.JTextField();
        txt_primeraLetra = new javax.swing.JTextField();
        txt_ultimaLetra = new javax.swing.JTextField();
        txt_letraCentral = new javax.swing.JTextField();
        txt_primeraPalabra = new javax.swing.JTextField();
        txt_palabraCentral = new javax.swing.JTextField();
        txt_ultimaPalabra = new javax.swing.JTextField();
        txt_repeticionesA = new javax.swing.JTextField();
        txt_repeticionesE = new javax.swing.JTextField();
        txt_repeticionesI = new javax.swing.JTextField();
        txt_repeticionesO = new javax.swing.JTextField();
        txt_repeticionesU = new javax.swing.JTextField();
        txt_palabrasPar = new javax.swing.JTextField();
        txt_palabrasImpar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_traduccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_abrir = new javax.swing.JMenuItem();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_guardar_como = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jmi_copiar = new javax.swing.JMenuItem();
        jmi_cortar = new javax.swing.JMenuItem();
        jmi_pegar = new javax.swing.JMenuItem();
        jmi_buscar = new javax.swing.JMenuItem();
        jmi_reemplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_texto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_texto.setToolTipText("");
        txt_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_textoActionPerformed(evt);
            }
        });

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        txt_longitud.setEditable(false);

        txt_totalPalabras.setEditable(false);

        txt_primeraLetra.setEditable(false);

        txt_ultimaLetra.setEditable(false);

        txt_letraCentral.setEditable(false);
        txt_letraCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_letraCentralActionPerformed(evt);
            }
        });

        txt_primeraPalabra.setEditable(false);
        txt_primeraPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_primeraPalabraActionPerformed(evt);
            }
        });

        txt_palabraCentral.setEditable(false);
        txt_palabraCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_palabraCentralActionPerformed(evt);
            }
        });

        txt_ultimaPalabra.setEditable(false);
        txt_ultimaPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultimaPalabraActionPerformed(evt);
            }
        });

        txt_repeticionesA.setEditable(false);
        txt_repeticionesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repeticionesAActionPerformed(evt);
            }
        });

        txt_repeticionesE.setEditable(false);

        txt_repeticionesI.setEditable(false);

        txt_repeticionesO.setEditable(false);

        txt_repeticionesU.setEditable(false);

        txt_palabrasPar.setEditable(false);

        txt_palabrasImpar.setEditable(false);

        jLabel1.setText("Longitud Texto");

        jLabel2.setText("Total Palabras");

        jLabel3.setText("Primera letra del Texto");

        jLabel4.setText("Ultima letra del Texto");

        jLabel5.setText("Letra Central del Texto");

        jLabel6.setText("Primera Palabra");

        jLabel7.setText("Palabra Central");

        jLabel8.setText("Última Palabra");

        jLabel9.setText("Repetciones \"A\",\"a\" ó \"á\"");

        jLabel10.setText("Repetciones \"E\",\"e\" ó \"é\"");

        jLabel11.setText("Repetciones \"I\",\"i\" ó \"í\"");

        jLabel12.setText("Repetciones \"O\",\"o\" ó \"ó\"");

        jLabel13.setText("Repetciones \"U\",\"u\" ó \"ú\"");

        jLabel14.setText("Palabras con cantidad de caracteres par:");

        jLabel15.setText("Palabras con cantidad de caracteres impar:");

        jLabel16.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        jLabel16.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_primeraPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_letraCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ultimaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_primeraLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_totalPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_procesar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_repeticionesO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_repeticionesU, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_palabrasPar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_repeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_repeticionesI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_repeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_ultimaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_palabraCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_palabrasImpar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_texto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addContainerGap())
            .addComponent(txt_traduccion, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_primeraLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ultimaLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_letraCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_primeraPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_palabrasPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_palabraCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_palabrasImpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ultimaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_traduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jm_archivo.setText("Archivo");

        jmi_abrir.setText("Abrir                  Ctrl+A");
        jmi_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abrirActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_abrir);

        jmi_guardar.setText("Guardar            Ctrl+G");
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_guardar);

        jmi_guardar_como.setText("Guardar Como  F12");
        jmi_guardar_como.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardar_comoActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_guardar_como);

        jMenuBar1.add(jm_archivo);

        jm_editar.setText("Editar");

        jmi_copiar.setText("Copiar                Ctrl+C");
        jmi_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_copiarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_copiar);

        jmi_cortar.setText("Cortar                 Ctrl+X");
        jmi_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cortarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_cortar);

        jmi_pegar.setText("Pegar                  Ctrl+P");
        jmi_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pegarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_pegar);

        jmi_buscar.setText("Buscar                 Ctrl+B");
        jmi_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_buscarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_buscar);

        jmi_reemplazar.setText("Reemplazar        Ctrl+R");
        jmi_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reemplazarActionPerformed(evt);
            }
        });
        jm_editar.add(jmi_reemplazar);

        jMenuBar1.add(jm_editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abrirActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = chooser.getSelectedFile();
            try {
                FileReader reader = new FileReader(file);
                BufferedReader bufferedReader = new BufferedReader(reader);
                String line;
                StringBuilder text = new StringBuilder();
                while ((line = bufferedReader.readLine()) != null) {
                    text.append(line).append("\n");
                }
                bufferedReader.close();
                txt_texto.setText(text.toString());
            }catch (IOException ex){
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jmi_abrirActionPerformed
    
    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed
        // TODO add your handling code here:
        if (currentFile == null) {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter(new FileNameExtensionFilter("Archivod de texto", "txt"));
            int returnVal = chooser.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                try {
                    FileWriter writer = new FileWriter(file);
                    writer.write(txt_texto.getText());
                    writer.close();
                    currentFile = file;
                    JOptionPane.showMessageDialog(this, "Archivo guardado correctamente");
                } catch (IOException ex) {
                    JOptionPane.showConfirmDialog(this, "Error al guardar el archivo: " + ex.getMessage());
                }
            }
        } else {
            try {
                FileWriter writer = new FileWriter(currentFile);
                writer.write(txt_texto.getText());
                writer.close();
                JOptionPane.showMessageDialog(this, "Archivo guardado correctamente");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jmi_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pegarActionPerformed
        // TODO add your handling code here:
        try {
            String contenidoPortapapeles = (String) Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);
            txt_texto.setText(txt_texto.getText() + contenidoPortapapeles);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No hay contendio en el portapapeles", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmi_pegarActionPerformed

    private void txt_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_textoActionPerformed

    private void jmi_guardar_comoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardar_comoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Archivo de Texto", "txt"));
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                FileWriter writer = new FileWriter(file);
                writer.write(txt_texto.getText());
                writer.close();
                JOptionPane.showMessageDialog(this, "Archivo Guardado Correctamente");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jmi_guardar_comoActionPerformed

    private void jmi_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_copiarActionPerformed
        // TODO add your handling code here:
        String seleccion = txt_texto.getSelectedText();
        if (seleccion != null) {
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            StringSelection seleccionTexto = new StringSelection(seleccion);
            clipboard.setContents(seleccionTexto, null);
        }
    }//GEN-LAST:event_jmi_copiarActionPerformed

    private void jmi_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cortarActionPerformed
        // TODO add your handling code here:
        String seleccion = txt_texto.getSelectedText();
        if (seleccion != null) {
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            StringSelection seleccionTexto = new StringSelection(seleccion);
            clipboard.setContents(seleccionTexto, null);
            txt_texto.replaceSelection("");
        }
    }//GEN-LAST:event_jmi_cortarActionPerformed

    private void jmi_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_buscarActionPerformed
        // TODO add your handling code here:
        String textoBuscar = JOptionPane.showInputDialog(this, "Ingrese la palabra a buscar:");
        if (textoBuscar != null) {
            String textoActual = txt_texto.getText();
            if (textoActual.contains(textoBuscar)) {
                JOptionPane.showMessageDialog(this, "La palabra '" + textoBuscar + "' se encontro en el texto.", "Resultado de la busqueda", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "La palabra '" + textoBuscar + "' no se encontro en el texto." , "Resultado de la busqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmi_buscarActionPerformed

    private void jmi_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reemplazarActionPerformed
        // TODO add your handling code here:
        String palabraOriginal = JOptionPane.showInputDialog(this, "Ingrese la palabra a reemplazar");
        if (palabraOriginal != null) {
            String palabraNueva = JOptionPane.showInputDialog(this, "Ingrese la palabra que reemplazara a '" + palabraOriginal + ":");
            if (palabraNueva != null) {
                String textoActual = txt_texto.getText();
                String textoReemplazado = textoActual.replace(palabraOriginal, palabraNueva);
                txt_texto.setText(textoReemplazado);
            }
        }
    }//GEN-LAST:event_jmi_reemplazarActionPerformed

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        String texto = txt_texto.getText();
        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El texto esta vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int longitudTexto = texto.length();
        txt_longitud.setText(String.valueOf(longitudTexto));
        
        String[] palabras = texto.split("\\s+");
        int totalPalabras = palabras.length;
        txt_totalPalabras.setText(String.valueOf(totalPalabras));
        
        String primeraLetra = String.valueOf(texto.charAt(0));
        txt_primeraLetra.setText(primeraLetra);
        
        String ultimaLetra = String.valueOf(texto.charAt(texto.length() - 1));
        txt_ultimaLetra.setText(ultimaLetra);
        
        int letraCentralIndex = longitudTexto / 2;
        String letraCentral = String.valueOf(texto.charAt(letraCentralIndex));
        txt_letraCentral.setText(letraCentral);
        
        String primeraPalabra = palabras[0];
        txt_primeraPalabra.setText(primeraPalabra);
        
        int palabraCentralIndex = totalPalabras / 2;
        String palabraCentral = palabras[palabraCentralIndex];
        txt_palabraCentral.setText(palabraCentral);
        
        String ultimaPalabra = palabras[totalPalabras - 1];
        txt_ultimaPalabra.setText(ultimaPalabra);
        
        int repeticionesA = contarRepeticiones(texto, "A", "a", "á");
        txt_repeticionesA.setText(String.valueOf(repeticionesA));

        int repeticionesE = contarRepeticiones(texto, "E", "e", "é");
        txt_repeticionesE.setText(String.valueOf(repeticionesE));

        int repeticionesI = contarRepeticiones(texto, "I", "i", "í");
        txt_repeticionesI.setText(String.valueOf(repeticionesI));

        int repeticionesO = contarRepeticiones(texto, "O", "o", "ó");
        txt_repeticionesO.setText(String.valueOf(repeticionesO));

        int repeticionesU = contarRepeticiones(texto, "U", "u", "ú");
        txt_repeticionesU.setText(String.valueOf(repeticionesU));
        
        String palabrasPar = obtenerPalabrasPar(palabras);
        txt_palabrasPar.setText(palabrasPar);

        String palabrasImpar = obtenerPalabrasImpar(palabras);
        txt_palabrasImpar.setText(palabrasImpar);
        
        String traduccion = traducirMurcielago(texto);
        txt_traduccion.setText(traduccion);
    }//GEN-LAST:event_btn_procesarActionPerformed

    private String traducirMurcielago(String texto) {
        String traduccion = "";
        for (char c : texto.toCharArray()) {
            int codigoAscci = (int) c;
            traduccion += String.valueOf(codigoAscci) + " ";
        }
        return traduccion.trim();
    }
            
    private void txt_letraCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_letraCentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_letraCentralActionPerformed

    private void txt_primeraPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_primeraPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_primeraPalabraActionPerformed

    private void txt_palabraCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_palabraCentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_palabraCentralActionPerformed

    private void txt_ultimaPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultimaPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultimaPalabraActionPerformed

    private void txt_repeticionesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repeticionesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repeticionesAActionPerformed

    private int contarRepeticiones(String texto, String letraMayuscula, String letraMinuscula, String letraTilde) {
        int contador = 0;
        for (int i = 0; i< texto.length(); i++) {
            char letra = texto.charAt(i);
            if (letra == letraMayuscula.charAt(0) || letra == letraMinuscula.charAt(0) || letra == letraTilde.charAt(0)) {
                contador++;
            }
        }
        return contador;
    }
    
    private String obtenerPalabrasPar(String[] palabras) {
        StringBuilder palabrasPar = new StringBuilder();
        for (String palabra : palabras) {
            if (palabra.length() % 2 == 0) {
                palabrasPar.append(palabra).append(" ");
            }
        }
        return palabrasPar.toString().trim();
    }

    private String obtenerPalabrasImpar(String[] palabras) {
        StringBuilder palabrasImpar = new StringBuilder();
        for (String palabra : palabras) {
            if (palabra.length() % 2 != 0) {
                palabrasImpar.append(palabra).append(" ");
            }
        }
        return palabrasImpar.toString().trim();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenuItem jmi_abrir;
    private javax.swing.JMenuItem jmi_buscar;
    private javax.swing.JMenuItem jmi_copiar;
    private javax.swing.JMenuItem jmi_cortar;
    private javax.swing.JMenuItem jmi_guardar;
    private javax.swing.JMenuItem jmi_guardar_como;
    private javax.swing.JMenuItem jmi_pegar;
    private javax.swing.JMenuItem jmi_reemplazar;
    private javax.swing.JTextField txt_letraCentral;
    private javax.swing.JTextField txt_longitud;
    private javax.swing.JTextField txt_palabraCentral;
    private javax.swing.JTextField txt_palabrasImpar;
    private javax.swing.JTextField txt_palabrasPar;
    private javax.swing.JTextField txt_primeraLetra;
    private javax.swing.JTextField txt_primeraPalabra;
    private javax.swing.JTextField txt_repeticionesA;
    private javax.swing.JTextField txt_repeticionesE;
    private javax.swing.JTextField txt_repeticionesI;
    private javax.swing.JTextField txt_repeticionesO;
    private javax.swing.JTextField txt_repeticionesU;
    private javax.swing.JTextField txt_texto;
    private javax.swing.JTextField txt_totalPalabras;
    private javax.swing.JTextField txt_traduccion;
    private javax.swing.JTextField txt_ultimaLetra;
    private javax.swing.JTextField txt_ultimaPalabra;
    // End of variables declaration//GEN-END:variables
}
